apiVersion: v1
kind: Namespace
metadata:
  name: "###ZARF_VAR_TARGET_NAMESPACE###"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-foundation
  namespace: "###ZARF_VAR_TARGET_NAMESPACE###"
data:
  message: "###ZARF_VAR_MESSAGE###"
